spring:
  profiles:
    active: pro

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  resources:
    static-locations: /META-INF/

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8081
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

logging:
  config: classpath:log4j2.yml

mybatis:
  type-aliases-package: com.qwwuyu.gs
  mapper-locations: classpath*:mapper/*.xml
