spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://inputIP:inputPORT/server?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: input
    password: input

env:
  private-key: input #注册私钥
  public-key: input #注册公钥
